#!/bin/bash
# this is written for idmain on localhost to ldx localhost 8282 to 8203
#  mlcp import after curling out a particular lccn ($1)  from nametitles in id-main
# covert using yaz; no load; post to lccn directory
# called by bibrecs/rnc
# curls the xml from id, stores in source, as .xml, converts using yaz to source/.rdf
# watch-auths moves them to load before running rnl (copied from rbl)

source  /marklogic/id/lds-bf-github/src/main/ml-modules/root/prep/config auths
CURDIR=`echo $PWD`
LCCN=$1 

curl -L http://idwebvlp03.loc.gov/authorities/names/$LCCN.marcxml.xml > $SOURCE_UNPROCESSED/single/$LCCN.xml
chmod 775 $SOURCE_UNPROCESSED/single/$LCCN.xml
chgrp marklogic $SOURCE_UNPROCESSED/single/$LCCN.xml

yaz-record-conv auth2bibframe2/auths-conv.xml $SOURCE_UNPROCESSED/single/$LCCN.xml |  sed -e "s|idwebvlcp03.loc.gov|id.loc.gov|g" | sed -e "s|mlvlp04.loc.gov:8080|id.loc.gov|g" > $SOURCE_PROCESSED/single/$LCCN.rdf

rm $SOURCE_UNPROCESSED/single/$LCCN.xml


chmod 775 $SOURCE_PROCESSED/single/$ID*
chgrp marklogic $SOURCE_PROCESSED/single/$ID*
