#!/bin/bash
#soup to nuts; curl the permalink lccn marcxml if bib is not in db, save in "sources"
# use yaz conversion to save as rdf in "sourceload"
#
#curl metaproxy or run yaz for a singleton

BIBID=$1

#B=$(echo "${BIBID//c/}")
#BIBID=$("${B//0/}")
echo $BIBID

tm=$(date '+%H-%M-%S')
echo "---------------"
echo curling permalink for lccn: $BIBID/marcxml
# sru:
curl https://lccn.loc.gov/$BIBID/marcxml    | sed -e "s|\[from old catalog\]||g"   > sources/singleton.$BIBID.xml

echo done curling 

ls -l sources/singleton.$BIBID*

#cat sources/singleton.$BIBID.xml

chmod 775 sources/*
chgrp marklogic sources/*

CURDIR=`echo $PWD`

M2BFDIR=/marklogic/id/marc2bibframe2
   yaz-record-conv  $M2BFDIR/record-conv.current.xml  $CURDIR/sources/singleton.$BIBID.xml >$CURDIR/sources/singleton.$BIBID.tmp.rdf
 uconv -f utf8 -t utf8 -x nfc < $CURDIR/sources/singleton.$BIBID.tmp.rdf   > $CURDIR/sources/singleton.$BIBID.tmp2.rdf

 xsltproc modules/graphiphy.xsl  sources/singleton.$BIBID.tmp2.rdf  > sourceload/singleton.$BIBID.rdf
#rm $CURDIR/sources/singleton.$BIBID*



chmod 775 sourceload/*
chgrp marklogic sourceload/*
ls -l sourceload/singleton.$BIBID*
echo did you get the rdf in sourceload?

TODAY=`date +%Y-%m-%d`

echo "load date  = $TODAY"
echo loading
MLCPPATH=/marklogic/id/id-prep/mlcp/bin
PASSWD=`/marklogic/id/id-prep/marc/keys/passwd-ml.sh`
 
 $MLCPPATH/mlcp.sh import  \
       -host localhost \
        -port 8203 \
        -username id-admin \
        -password $PASSWD \
	-input_file_pattern singleton.$BIBID.rdf \
	-input_file_path /marklogic/id/natlibcat/admin/bfi/bibrecs/sourceload \
	-output_uri_replace "/marklogic/id/natlibcat/admin/bfi/bibrecs/sourceload/,''"  \
	-output_collections /bibframe-process/,/processing/load/bibs/$TODAY/,/bibframe-process/yaz-reload/ \
	-output_permissions lc_read,read,lc_read,execute,id-admin-role,update,lc_xmlsh,update \
	-input_file_type documents \
	-transform_module /admin/bfi/bibrecs/corb-bibframe-process-yazbib-files.xqy \
	-transform_namespace "http://loc.gov/ndmso/marc-2-bibframe-yaz/" \
	-document_type xml \
	-aggregate_record_element RDF \
    	-aggregate_record_namespace http://www.w3.org/1999/02/22-rdf-syntax-ns# \
        -mode local 

 echo $BIBID loaded?
# mv   sourceload/singleton.$BIBID.rdf loaded/

