#!/bin/bash
# rbi does convert, load. Use rbc a bunch of times then one rbl to load them

#curl metaproxy or run yaz for a singleton


BIBID=$1

tm=$(date '+%H-%M-%S')
curl "http://lx2.loc.gov:210/LCDB?query=rec.id=$BIBID&recordSchema=marcxml&maximumRecords=1"  | sed -e "s|\[from old catalog\]||g"   > source/singleton.$BIBID.xml
line=$(grep -n "marc:record"  source/singleton.$BIBID.xml)
echo $line
read x
# curl "http://mlvlp04.loc.gov:8230/resources/bibs/$BIBID.xml"  | sed -e "s|\[from old catalog\]||g"   > source/singleton.$BIBID.xml
chmod 775 source/*
chgrp marklogic source/*

CURDIR=`echo $PWD`

M2BFDIR=/marklogic/id/marc2bibframe2
   yaz-record-conv  $M2BFDIR/record-conv.xml  $CURDIR/source/singleton.$BIBID.xml >$CURDIR/singleload/singleton.$BIBID.rdf
chmod 775 $CURDIR/singleload/*
chgrp marklogic $CURDIR/singleload/*

rm $CURDIR/source/singleton.$BIBID*
