#!/bin/bash

#modified to work like bibdaily4 (load only a single record by ID)
#curl metaproxy or run yaz for a singleton and load right away


source /marklogic/id/lds-bf-github/src/main/ml-modules/root/prep/config  bibrecs

./source2rdf_single.sh $1 $2


 mv  $SOURCE_PROCESSED/single/$1*  $LOAD_UNPROCESSED/single/
 echo  $LOAD_UNPROCESSED/single/
 ls -l  $LOAD_UNPROCESSED/single/
 
	  
./loadrdf_single.sh

