#!/bin/bash
#curl single bib and overwrite, either bibid or lccn
# this version reloads but does nto try to merge, using $NOMERGE parameter


source /marklogic/id/lds-bf-github/src/main/ml-modules/root/config  bibrecs

./source2rdf_single.sh $1 $2


CURDIR=`echo $PWD`

# do not check for edited content before loading.
NOMERGE="NOMERGE"


 mv  $SOURCE_PROCESSED/single/$1*  $LOAD_UNPROCESSED/single/
 echo  $LOAD_UNPROCESSED/single/
 ls -l  $LOAD_UNPROCESSED/single/

	  
./loadrdf_single.sh "NOMERGE"

